---
abstract: 'Communicate between processes with Morse signals.'
author:
  - 'Vincent Pit <perl@profvince.com>'
build_requires:
  Bit::MorseSignals: 0.05
  Carp: 0
  Config: 0
  Data::Dumper: 0
  Exporter: 0
  ExtUtils::MakeMaker: 0
  POSIX: 0
  Test::More: 0
  Time::HiRes: 0
  base: 0
  utf8: 0
configure_requires:
  Config: 0
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-MorseSignals
no_index:
  directory:
    - t
    - inc
requires:
  Bit::MorseSignals: 0.05
  Carp: 0
  POSIX: 0
  Time::HiRes: 0
  base: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Name=IPC-MorseSignals
  homepage: http://search.cpan.org/dist/IPC-MorseSignals/
  license: http://dev.perl.org/licenses/
  repository: http://git.profvince.com/?p=perl%2Fmodules%2FIPC-MorseSignals.git
version: 0.16
